# Creating DataFrames

Many ways to do it!

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = np.random.random(size=(5, 3))
print(data)

# Common 2D array and columns method
df = pd.DataFrame(data=data, columns=["A", "B", "C"])
df

[[0.4415726  0.70963911 0.80978624]
 [0.10725625 0.038987   0.29671945]
 [0.69793772 0.04262658 0.00947945]
 [0.27181398 0.54219944 0.41854397]
 [0.76592333 0.32546107 0.34473648]]


A         B         C
0  0.441573  0.709639  0.809786
1  0.107256  0.038987  0.296719
2  0.697938  0.042627  0.009479
3  0.271814  0.542199  0.418544
4  0.765923  0.325461  0.344736

In [5]:
# A dictionary of columns
df = pd.DataFrame(data={"A": [1, 2, 3], "B": ["Sam", "Alex", "John"]})
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [6]:
# Or a list of rows (ie tuples) with a dtype
dtype = [("A", np.int), ("B", (np.str, 20))]
data = np.array([(1, "Sam"), (2, "Alex"), (3, "John")], dtype=dtype)
df = pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [7]:
# Or the dictionary based version of list of rows
data = [{"A": 1, "B": "Sam"}, {"A": 2, "B": "Alex"}, {"A": 3, "B": "John"}]
df = pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  John